services:
  krakweb.request_id.monolog_processor:
      class: Krakweb\RequestId\Monolog\Processor\RequestIdProcessor
      tags:
       - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
       - { name: monolog.processor }
